# Enforce sinks and restrict policy names to 'react-eval' and 'default'.
<LocationMatch "^/[^/]+/enforce-named/">
    Header always set Content-Security-Policy "require-trusted-types-for 'script'; trusted-types react-eval default; report-uri /api/csp-report"
</LocationMatch>
